plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'application'
    id 'java'
    id 'maven-publish'
}

apply plugin: 'java'
apply plugin: 'com.gradleup.shadow'

group = project.group_id
version = project.version_name

publishing {
    publications {
        gpr(MavenPublication) {
            groupId = project.group_id
            artifactId = project.artifact_id
            version = project.version_name

            from components.java
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

subprojects {
    repositories {
        mavenCentral()
        maven {
            url 'https://jitpack.io'
        }
    }
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.25.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    implementation 'com.google.guava:guava:33.5.0-jre'
    implementation 'io.netty:netty-all:4.2.14.Final'
    implementation 'com.github.oshi:oshi-core:6.6.3'
    implementation "com.github.cao-awa:Cason:$project.cason_version"
    implementation "com.github.cao-awa:CaperTML:$project.capertml_version"
//    compileOnly 'org.junit.jupiter:junit-jupiter-api:6.1.3'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    compileOnly 'org.junit.jupiter:junit-jupiter'
    compileOnly 'org.junit.platform:junit-platform-engine:6.1.3'
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

application {
    mainClass = project.mainClass
}

shadowJar {
    archiveBaseName.set('Kalmia')
    archiveVersion.set(project.version_name)
    archiveClassifier.set('')

    getExcludes().add("org.junit.jupiter::")
}

kotlin {
    jvmToolchain(21)
}

tasks.named("distTar") {
    dependsOn shadowJar
}

tasks.named("startScripts"){
    dependsOn shadowJar
}

tasks.named("startShadowScripts") {
    dependsOn jar
}

test {
    useJUnitPlatform()
}

tasks.withType(AbstractTestTask).configureEach {
    failOnNoDiscoveredTests = false
}